# Generated by Django 5.2 on 2025-04-24 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakeibo_app', '0002_category_alter_expense_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(choices=[(1, '1日'), (2, '2日'), (3, '3日'), (4, '4日'), (5, '5日'), (6, '6日'), (7, '7日'), (8, '8日'), (9, '9日'), (10, '10日'), (11, '11日'), (12, '12日'), (13, '13日'), (14, '14日'), (15, '15日'), (16, '16日'), (17, '17日'), (18, '18日'), (19, '19日'), (20, '20日'), (21, '21日'), (22, '22日'), (23, '23日'), (24, '24日'), (25, '25日'), (26, '26日'), (27, '27日'), (28, '28日'), (29, '29日'), (30, '30日'), (31, '31日')], verbose_name='支払日')),
                ('amount', models.IntegerField(verbose_name='金額')),
                ('start_date', models.DateField(verbose_name='開始日')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='終了日')),
                ('memo', models.TextField(blank=True, verbose_name='メモ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kakeibo_app.card', verbose_name='カード')),
            ],
        ),
    ]
